/** @type {import('tailwindcss').Config} */
const plugin = require("tailwindcss/plugin");

module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      boxShadow: {
        piBoxShadow: "0px 20px 30px rgba(0, 0, 0, 0.1)",
      },
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
        guruWayThin: ["Guruway-Thin"],
        guruWayLight: ["Guruway-Light"],
        guruWayBold: ["Guruway-Bold"],
        guruWaySemiBold: ["Guruway-SemiBold"],
        guruWayMedium: ["Guruway-Medium"],
        guruWayRegular: ["Guruway-Regular"],
      },
      colors: {
        transparent: "transparent",
        PiWhiteBackground: "#FFFFFF",
        PiGrayBackground: "#F9F9F9",
        PiGradentfrom: "#FF7542",
        PiGradentto: "#FE4501",
        PiButton: "#FE8551",
        Pilogo: "#D85A49",
        PiHeader: "#CEE8E0",
        PiSubheader: "#FFEBE4",
        PiBlack: "#1D1B19",
        PiGrey: "#939393",
        PiBorderGrey: "#e6e6e6",
        PiCards: "#FDF5F2",
        PiLink: "#2420FA",
        PiSpeed: "#BEFDA9",
        PiDocument: "#FEFAC6",
        PiFooter: "#E4F2EE",
        PiVerify: "#CEE8E0",
        PiCardMegaMenuHover: "#F3EDFF",
        PiBullet: "#115DCE",
        PiAttract: "#FF7542",
        PiGoogleStar: "#FFBD00",
        PiCardBorder: "#54545426",
        PiLightYellow: "#FBF818",
        GuruInteractive: "#590DE1",
        GuruButton: "#3EF518",
        GuruBlack: "#0E0F0C",
        GuruGrey: "#6A6C6A",
        GuruLightGrey: "#F4EEFF",
        GuruNeutral: "#F3F3F3",
        GuruWhite: "#FFFFFF",
        GuruRed: "#FF3566",
        GuruCardGradentFrom: "#E4FFDE",
        GuruCaradGradentTo: "#F3ECFF",
        GuruHeroBlueGradientFrom: "#AB7CF7",
        GuruHeroBlueGradientTo: "#8B4BF6",
        GuruGreenPurpleGradientFrom: "#F0E8FF",
        GuruGreenPurpleGradientTo: "#E4FFDE",
        GuruDarkGreen: "#38761D",
        GuruLightGreen: "#43FF64D9",
        GuruOrange: "#FF9900",
        GuruYellow: "#F1F518",
        GuruNormalGreen: "#02E0AB",
        GuruBgInteractive: "#7D35FF",
        GuruLightGreyNew: "#DEDEE2",
        PiAd: "#FF3566",
        GuruLightGreyGradientFrom: "#DEDEE2",
        GuruLightGreyGradientTo: "#FFFFFF",
        GuruPurple: "#590DE126",
        GuruDarkBlue: "#200757",
        GuruWarning: "#D7260D",
        GuruLavender: "#D5BFFC",
        GuruOrangeGradentFrom: "#FFAD08",
        GuruOrangeGradentTo: "#FF763C",
        GuruAd: "#FF3566",
        GuruAdLight: "#FBE9E7",
        GuruCoupon: "#FFE7ED",
      },
      screens: {
        sm: "480px",
        md: "769px",
        lg: "992px",
        xl: "1200px",
        xxl: "1400px",
      },
      keyframes: {
        FirstTick: {
          "0%": { visibility: "hidden" },
          "10%": { visibility: "hidden" },
          "20%": { visibility: "hidden" },
          "30%": { visibility: "hidden" },
          "40%": { visibility: "hidden" },
          "50%": { visibility: "visible" },
          "60%": { visibility: "visible" },
          "70%": { visibility: "visible" },
          "80%": { visibility: "visible" },
          "100%": { visibility: "visible" },
        },
        SecondTick: {
          "0%": { visibility: "visible" },
          "10%": { visibility: "visible" },
          "20%": { visibility: "hidden" },
          "30%": { visibility: "hidden" },
          "40%": { visibility: "hidden" },
          "50%": { visibility: "hidden" },
          "60%": { visibility: "hidden" },
          "70%": { visibility: "visible" },
          "80%": { visibility: "visible" },
          "100%": { visibility: "visible" },
        },
        ThirdTick: {
          "0%": { visibility: "visible" },
          "10%": { visibility: "visible" },
          "20%": { visibility: "visible" },
          "30%": { visibility: "visible" },
          "40%": { visibility: "hidden" },
          "50%": { visibility: "hidden" },
          "60%": { visibility: "hidden" },
          "70%": { visibility: "hidden" },
          "80%": { visibility: "hidden" },
          "100%": { visibility: "visible" },
        },
        mockpen: {
          "0%": { transform: "translate(-10%)" },
          "100%": { transform: "translate(30%)" },
        },
        penline: {
          "0%": { width: "1px" },
          "100%": { width: "48px" },
        },
        arrowmove: {
          "0%": { opacity: "1", left: "80px", top: "40px" },
          "50%": { left: "0px", top: "0px" },
          "70%": { opacity: "0" },
        },
        hideplaybutton: {
          "0%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        displaypausebutton: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        "PiHome-first-tick": "FirstTick 3s linear infinite",
        "PiHome-second-tick": "FirstTick 4s linear infinite",
        "PiHome-third-tick": "FirstTick 5s linear infinite",
        PiMockPenAnim: "mockpen 1s linear infinite",
        PiMockLineAnim: "penline 1s linear infinite",
        PiVideoCoursesArrowAnim: "arrowmove 2s linear infinite",
        PiVideoCoursesPlaybtn: "hideplaybutton 2s linear infinite",
        PiVideoCoursesPausebtn: "displaypausebutton 2s linear infinite ",
      },
    },
  },
};
